print("Enter your name")
a=str(input())
print("Enter your age")
b=str(input())
print("Enter you Qualification")
c=str(input())
print("Enter years  of Experience")
d=str(input())
print("name- "+a)
print("Age- "+b)
print("Qulification- "+c)
print("Experience- "+d)
